Add Assetto Corsa
CubeCoders/AMPTemplates pull request #194
Opened 2022-09-20 12:53 UTC by Greelan

Adds Assetto Corsa dedicated server.

User join/leave/chat regex to be confirmed.

2022-09-24 02:21 UTC, IceOfWraith requested changes
I cannot get it to go on the server list, but I can't get it to even outside of AMP. So I'm blaming that on my own incompetence.

2022-09-24 02:21 UTC, IceOfWraith commented on assetto-corsaconfig.json
> +        "Placeholder":"0-100",
Add Min/Max instead?

2022-09-24 02:21 UTC, IceOfWraith commented on assetto-corsaconfig.json
> +        "Placeholder":"89",
Nothing to change here. I just really hate that it's 89 by default.

2022-09-24 03:41 UTC, Greelan commented
> 

I saw a reddit comment that you need to click "missing" in the browser to show all servers? Something to do with not supplying all metadata

2022-09-24 03:43 UTC, IceOfWraith commented
I can't even get it to start though. It said it's invalid and boot loops. Lol

2022-09-24 03:43 UTC, IceOfWraith commented
It loads up if I choose not to list publicly... But then there's no way to connect.

2022-09-24 03:44 UTC, Greelan commented
Sorry, start what? Take this to Discord?

2022-09-24 07:07 UTC, Greelan commented on assetto-corsaconfig.json
> +        "Placeholder":"0-100",
Done

2022-09-28 03:35 UTC, IceOfWraith approved these changes
As noted, I'm unable to connect to my own server. But this game is pretty convoluted in the way it only accepts certain settings. Competitions at least told why your server wasn't accepted. This one just fails. It seems to be configured right from guides I've seen so giving this the green light.

2022-09-28 04:38 UTC, Greelan commented
I'm not inclined to merge something that we can't test a connection to. If it's a settings issue (eg the player limit exceeding available cars in the entry list), maybe we can play around with those?

2022-10-03 13:09 UTC, Greelan commented
Verified now simply to be a router firewall issue stopping the server registering to the master server and therefore the game server started. With that fixed, the server starts fine.

2022-10-03 14:06 UTC, IceOfWraith approved these changes
Very good. Thanks for testing it random user!

2022-10-03 14:08 UTC, merged