Add Day of Dragons
CubeCoders/AMPTemplates pull request #195
Opened 2022-09-21 12:22 UTC by Greelan

Adds Day of Dragons dedicated server.

Notes:
- Supplies Game.ini but basic settings only currently in UI
- Steam init issue on Windows to be resolved (doesn't open QueryPort as a result)
- Regex to be added

2022-09-21 12:31 UTC, IceOfWraith commented
Pls stop. I can't keep up!

2022-09-21 12:38 UTC, Greelan commented
Lol, take your time. I still have a couple of yours to look at. This one is pretty much there but more finessing needed

2022-09-21 12:46 UTC, Shinynecrid commented
> Pls stop. I can't keep up!

Lmao

2022-10-03 03:43 UTC, Greelan commented
Based on feedback and logs from a user on Discord, there seems to be nothing logged by the server for user join/leave/chat. So nothing for the regex. 

The user otherwise confirmed that the server is operating as expected. So this template is ready for review.

2022-10-03 23:53 UTC, IceOfWraith requested changes
Looks good. Don't have the game to test, but as mentioned it was tested by another user.

2022-10-03 23:53 UTC, IceOfWraith commented on day-of-dragonsmetaconfig.json
> +		"ConfigFormatRegex":"^(?<key>.+?)=(?<value>.*?)$"
Minor spacing issue on both Format lines.

2022-10-04 00:48 UTC, Greelan commented on day-of-dragonsmetaconfig.json
> +		"ConfigFormatRegex":"^(?<key>.+?)=(?<value>.*?)$"
Thanks, fixed

2022-10-04 00:50 UTC, IceOfWraith approved these changes
Very nice! Are you up to 50 yet? :p

2022-10-04 00:51 UTC, merged