Merged Valheim and Valheim Plus templates.
CubeCoders/AMPTemplates pull request #241
Opened 2022-11-27 21:20 UTC by gkuba

I decided to merge the two Valheim templates into one.

Removed:

- valheimplus.kvp
- Server category in Configuration

Added:

- Changed the saves folder name from Data to Saves for clarity to the user. 
- BepInEx and other needed EnvironmentVariables
- Valheim General Settings category in Configuration
- Valheim Plus Settings category in Configuration
- Moved the Steam Update and Valheim Plus downloads to the valheimupdates.json 
- A Install Valheim Plus toggle under Configuration -> Valheim Plus Settings
- Info box about configuring Valheim Plus until I can get the settings from the .cfg file added in a good way.

2022-11-27 23:11 UTC, IceOfWraith commented
I haven't reviewed this yet, but excited to see how it behaves! The one thing that we'll need to discuss that I see just from your summary is the saves folder. Changing that may cause issues for people with existing game saves that update their template. It may not be the case though, Have you tried that by chance?

2022-11-27 23:20 UTC, IceOfWraith commented
After some quick thought... Perhaps a rename command would solve that. Just rename the Data directory to Saves as an update stage on each OS.

2022-11-27 23:41 UTC, gkuba commented
I could add that to solve any potential issues with the directory name change.

2022-11-28 01:33 UTC, IceOfWraith commented
Never rush this stuff. Nobody is gonna be screaming that you get it done. Rest and come back to it. :)

2022-11-28 02:00 UTC, Greelan commented
Note that on some distros `cp` is aliased so that it interactively prompts for overwriting. The UT99 kvp is an example of how to work around that.

2022-11-28 02:52 UTC, gkuba commented
Yeah that was a copy pasta mistake. Its fixed now to use mv for less confusion after the conversion.

2022-11-28 02:54 UTC, gkuba commented
Ok I think that is all good to go for now. Tests on both Linux and Windows worked I even tested with an already existing Data folder. I'm going to leave this be for the night and get some sleep. Thanks for all the help guys!

2022-11-28 22:28 UTC, gkuba commented
Added the updated user Joined / Leaves server regex for issue #242

2022-12-02 21:32 UTC, gkuba commented
I haven't tested every config option for the Valheim Plus settings. I have tested the saves folder change as well as the BepInEx install without Valheim Plus. Both ware working on Linux and Windows.

2022-12-02 22:58 UTC, Greelan commented
Marked as draft pending testing of the config options

2022-12-17 08:20 UTC, IceOfWraith requested changes
First of all, let me say... Phenomenal work with this one! You should really be proud of what you accomplished by adding all these settings! I think you just took the lead for "The most lines put into a single config.json file". Lol

I've provided the replies for things that stuck out as an issue. I haven't fully tested yet until these get corrected in case they caused issues with the template. Most items are duplicated from copy/paste, or spelling errors. Nothing major in any cases. Please take a look and if I misreported something please feel free to respond to that review with a reason why I'm a dummy and mark them resolved. :)

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"; Apply the copied object rotation of the currently selected object in Advanced Editing Mode. Default Keypad8",
`; ` needs removed

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"; Copy the object rotation of the currently selected object in Advanced Editing Mode. Default Keypad7",
`; ` needs removed

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Camera Settings Enable",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Camera Settings Enable",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Camera Settings Enable",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Copy Object Rotation Hotkey",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Frementer Durration",
`Duration`

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Frementer Chest Detection Range",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Furnace Ignore Private Area Check",
Duplicated setting. Seems to be identical to the other with the same name.

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Ignore Private Area Check",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Ignore Private Area Check",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Kiln Auto Deposit",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Player Max Projectile Velicity",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Player Max Projectile Velicity",
`Velocity`

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Remove Damage Red Flash",
Seems to be duplicate setting of one above with same name.

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Tameable Settings Enable",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Wagon Base Mass",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Ward Range",
Duplicate DisplayName

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"clubs Stamina Usage",
Capital C

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"frost Magic Experience Values",
Capital F

2022-12-17 08:20 UTC, IceOfWraith commented on valheimconfig.json
> +    "FieldName":"GameClock.enabled",
Duplicate fieldname. Should be Brightness.enabled?

2022-12-17 09:02 UTC, gkuba commented
Well thanks for taking the time to look over this. Some I have already caught but I will go over this list and get them fixed and it pushed.

But yes there was a lot of copy / paste for all those sections and after the first 2k lines the text starts to blur together so again thanks for calling these out. 

The sad part is the next one to add by request is OdinsQoL and it will effectively double this.

2022-12-18 14:15 UTC, Greelan commented
Incredible work to get all this in! I haven't looked at it in detail, but I assume at some point when you recover from doing all this that you will do a proofread? Eg in the manifest I noticed various misspellings of "Durability", and line 844 includes extra words in the FieldName (likely copied from the Keywords).

2022-12-18 14:42 UTC, IceOfWraith requested changes

2022-12-18 14:42 UTC, IceOfWraith commented on valheimconfig.json
> +        "True": "True"
The right side values can be lowercase still. It's just the left side that was what AMP expects to be "True" or "False". Changing this broke the update stages. :)

2022-12-18 14:42 UTC, IceOfWraith commented on valheimconfig.json
> +        "True": "True"
Same here.

2022-12-18 14:44 UTC, IceOfWraith requested changes

2022-12-18 14:44 UTC, IceOfWraith commented on valheimconfig.json
> +    "FieldName":"FireSource.Ignore,Private,Area,Check",
Pointed out by Greelan.

2022-12-18 14:44 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Duriability of Armor",
`Durability` is misspelled multiple times.

2022-12-18 15:09 UTC, IceOfWraith requested changes

2022-12-18 15:09 UTC, IceOfWraith commented on valheimconfig.json
> +    "ParamFieldName":"Items.enable",
These should all be `...enabled` with a 'd" on the end. As it is, the settings do not update.

2022-12-18 15:34 UTC, IceOfWraith requested changes
Okay, I think I caught all the spelling issues that Greelan was referring to. Please, be sure to do a find/replace on all because I only marked one instance of each misspelling. There were more for some of them.

Honestly, less mistakes than I'd expect with 4,000 lines! I know with Space Engineers I had quite a few to revise. Lol

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description": "Password that clients must supply in order to connect. NOTE: Minimum password length is 5 characters & Password cant be in the server name. Default Password: 12345",
`can't` is missing the apostrophe.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"Enable sleeping on only unclaimed beds without setting bed as spawn. th this option enabled only beds that are not claimed by other players can be slept on without setting spawn-po
`th this`

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"Stops Auto Fuel looking for fuel when there is at leasts this quantity of Coal in nearby chests",
`least` with an extra s.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"The Duribility of armor. The value 50 will increase the durability from 100 to 150. The value -50 will reduce the durability from 100 to 50.",
`Durability` spelled another way again.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"The settings on this page are spit up into sections. The start of a section will be labled with \"sectionName Enable\" the setting in-between are only modifiable if that section is
`labeled` spelling.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"The settings on this page are spit up into sections. The start of a section will be labled with \"sectionName Enable\" the setting in-between are only modifiable if that section is
`enabled` spelled wrong.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"This option prevents crafting to pull items from warded areas if the player doesnt have access to it.",
`doesn't` missing apostrophe.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Description":"With this enabled you will receive the same exploration progression as other players on the server. This will also enable the option for the server to sync everyones exploration pr
`everyone's` missing apostrophe.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Disable Encumberance",
`encumbrance` spelled wrong.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"Map Exporation Radius",
`Exploration` spelled wrong.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "DisplayName":"\"I Hvae Arrived\" Message",
`Have` spelled wrong.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Keywords":"Chat,Norlam,Distance",
`Normal` spelled wrong.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Keywords":"Food,Degredation,Over,Time",
`Degradation` spelled wrong.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Keywords":"Stamina,Encombered,Drain",
`encumbered` spelled wrong.

2022-12-18 15:34 UTC, IceOfWraith commented on valheimconfig.json
> +    "Keywords":"Stamina,Regen,Dealy",
`Delay` spelled wrong.

2022-12-18 23:57 UTC, gkuba commented
Ok I think I got all that. Thanks you guys for looking over this you can clearly see the days I wasn't feeling well at all but couldn't lay down any longer. Sorry about the mess. 

I double checked there shouldn't be any more mixed up FieldName and Keywords fields.

2022-12-22 23:21 UTC, IceOfWraith approved these changes
I've tested the basic functionality and spot checked settings. It seems to be working as expected. Very nicely done!

2022-12-22 23:21 UTC, merged