Add ARK: Survival Evolved
CubeCoders/AMPTemplates pull request #266
Opened 2022-12-30 05:40 UTC by Greelan

Adds ARK: Survival Evolved

Associated comments: https://discord.com/channels/266012086423912458/1046205513970495538/1048454006831325244

2022-12-30 05:41 UTC, IceOfWraith commented
You're the best. <3

2023-01-14 18:03 UTC, IceOfWraith requested changes
This was a beast to review. But I gotta say, you did an EXTREMELY good job on it. The mod handling is a thing of dreams. I don't know of any provider that offers this level of ease for Ark. Very nice work.

I didn't notice any typos or formatting issues. There are two items I've put for feedback/changes though.

2023-01-14 21:44 UTC, Greelan commented on ark-seconfig.json
> +        "DisplayName":"Player Limit",
Done

2023-01-14 21:44 UTC, Greelan commented on ark-seconfig.json
> +        "DisplayName":"MultiHome IP Binding",
That's the default when it is left blank.

2023-01-14 21:46 UTC, Greelan commented
Thanks for doing the review - 'twas a beast to review, and more of a beast to write. I'd say the most involved template I've done. Hopefully the community sees value in it.

2023-01-14 22:37 UTC, IceOfWraith submitted a review, later dismissed
They definitely will.

2023-01-14 23:26 UTC, Greelan commented
Will wait for 2.4.1.4 to drop before merging, as it needs some elements currently in Nightly and the MinAMPVersion does not actually prevent an instance being created on an earlier version.

2023-01-14 23:47 UTC, IceOfWraith commented
Mike will also want to mark the other Legacy when he releases.

2023-02-20 16:32 UTC, IceOfWraith approved these changes
Yes, yes I did. *smug face*

2023-02-20 18:34 UTC, merged