Full Windows Support For Stormworks
CubeCoders/AMPTemplates pull request #450
Opened 2023-08-29 06:03 UTC by JonathanArendt

After much testing, added full support for Stormworks Dedicated Server for AMP on Windows. The server is able to start, stop, update. Added all of the configuration options to the config manifest to add support for editing the server config file as little as possible, the only outstanding features are Linus support. And the ability to manage whitelist, blacklist, admin, ect, within AMP, this is in part to a lack of the ability to import a list with the same ID, and in part due to how the game's config is.

2023-09-01 02:12 UTC, IceOfWraith commented
It looks like @Greelan added Linux support and you've done some extra clean up also. Is this ready for review? I'll knock it out this weekend if so.

2023-09-01 02:27 UTC, JonathanArendt commented
@IceOfWraith I have changes I have not pushed yet, one to fix a bug with whitelist being enabled by default, and I need to test what, AMP will do with muliple tags with the same index, (Idealy, amp should set at least one admin, so then the other whitelist/blacklists, can be handeled in game. And if that doesn't work I will had type Hidden boxes for instructions on setting up permissions,. All that said, I'm going to test a few more things, and then I'll let you know when It's good. Should have it ready by this weekend.

2023-09-01 02:33 UTC, IceOfWraith commented
No rush! I just didn't want it waiting on me. :)

2023-09-01 03:21 UTC, Greelan commented
I still need to do further review too

2023-09-01 06:02 UTC, JonathanArendt commented
All good, I was just going over some spelling ;), and other small things. Everything should be good now, I added a text field for admin, it sets the first admin in the list on the xml and that's it. As added in the notes, almost everything else can be controlled from in game.

2023-09-01 06:04 UTC, JonathanArendt commented
At this time, I have everything set up and ready for review. I would ask that you read over some of the "documentation" within the settings menus for any spelling issues and anything else that may need to be reworded or clarified.

2023-09-01 06:06 UTC, JonathanArendt commented
@IceOfWraith I'm going to work on typing up some information for you add in the docs for Additional Information relating to game permissions, in game commands, and how to setup Whitelists.

2023-09-01 07:03 UTC, JonathanArendt commented
@IceOfWraith I just pushed stormworksguide.md, this is really just a rough draft for the discourse server, I read that discourse uses Markdown so sorry if that's extra work for you, lol. Feel free to rewrite, reformat, add, remove, ect, to this. It's simply the information that I felt would feel crowded on the settings menu. Let me know if I need to add any of the information to the settings menu.

2023-09-01 07:04 UTC, JonathanArendt commented
@Greelan I'm not sure what steps are needed for Linux support so I need to add any additional settings or information for the guide, feel free to add to it or let me know.

2023-09-01 07:05 UTC, Greelan commented
It just needs Wine, desirably Wine 8. So either use docker or install wine 8 on the host. The docker policy box has that info.

2023-09-01 08:01 UTC, Greelan commented
> I read that discourse uses Markdown so sorry if that's extra work for you, lol. 

.md on GH is markdown too lol

2023-09-01 08:04 UTC, JonathanArendt commented
Lol, I know that it's markdown, I'm not sure if markdown is actually what's used on discourse, lol. I know some blogs use other languages, lol.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Greelan ***@***.***>
Sent: Friday, September 1, 2023 3:01:10 AM
To: CubeCoders/AMPTemplates ***@***.***>
Cc: SaruanTheWhite ***@***.***>; Author ***@***.***>
Subject: Re: [CubeCoders/AMPTemplates] Add Stormworks (PR #450)


I read that discourse uses Markdown so sorry if that's extra work for you, lol.

.md on GH is markdown too lol

—
Reply to this email directly, view it on GitHub<https://github.com/CubeCoders/AMPTemplates/pull/450#issuecomment-1702336760>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AD66A2CDEUSTZDPLOM62KZLXYGI4NANCNFSM6AAAAAA4CM3R5U>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-09-01 08:05 UTC, Greelan commented
Yes, discourse uses markdown

2023-09-03 03:25 UTC, JonathanArendt commented
Have either of you done any further review? I just got off work and wanted to check if there was any outstanding issues that need to be worked on?

2023-09-03 03:27 UTC, IceOfWraith commented
I think I'm just holding for Greelan to finish his reviewing.

2023-09-03 03:30 UTC, JonathanArendt commented
Sounds good, I know it's a holiday weekend, (at least for us in the US (don't know where you all are form)) so don't know if that means there will be more work done on this or less, lol.  Either way, it's all good, I'll be here if there's any changes to be made this weekend.

2023-09-03 03:38 UTC, IceOfWraith commented
I'm in the US so definitely spending time on AMP. When he says he's good I'll go through and do any followup.

2023-09-03 03:39 UTC, JonathanArendt commented
Sounds good to me, thanks Ice!

________________________________
From: IceOfWraith ***@***.***>
Sent: Saturday, September 2, 2023 10:38:40 PM
To: CubeCoders/AMPTemplates ***@***.***>
Cc: SaruanTheWhite ***@***.***>; Author ***@***.***>
Subject: Re: [CubeCoders/AMPTemplates] Add Stormworks (PR #450)


I'm in the US so definitely spending time on AMP. When he says he's good I'll go through and do any followup.

—
Reply to this email directly, view it on GitHub<https://github.com/CubeCoders/AMPTemplates/pull/450#issuecomment-1703998054>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AD66A2FQDKIQZ67XDRER2MTXYP3UBANCNFSM6AAAAAA4CM3R5U>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-09-03 12:34 UTC, Greelan commented
I will get to it this week

2023-09-08 05:41 UTC, Greelan commented
@JonathanArendt , I've committed some clean-ups to the config manifest. I still need to be do testing on the settings to confirm they write correctly.

Couple of things:
- I suggest that the Start Island setting list be re-ordered in alphabetical order, to help people find islands
- If the Day & Night Length setting can only be in increments of 10, is the MinValue correct at 1? Would it be better for this to be an enum, with the valid settings specified (10, 20, 30 etc)?

I haven't looked at your guide in detail. On a quick skim I thought it could be with some tidy up (typos etc) and also some bits should be re-written, as it wasn't clear what they actually meant. Also, it shouldn't be in the PR.

2023-09-08 05:59 UTC, Greelan commented
BTW, the admins setting does not appear to write anything to the config file

2023-09-08 06:28 UTC, JonathanArendt commented
So for the day night setting, a minimum of one is correct, since you can't have zero time, 1 is the minimum setting and after that you it's even 10s. (not me, that's the devs, I could go on, but just look at how the console works, lol)

2023-09-08 06:32 UTC, JonathanArendt commented
As for the list, I used the ordering on the guide, It's listed based on the island that the player starts on (and that includes dlc bases on the dlc maps). I used the same ordering on the server setup guide, but i could change the order of it, if that makes it more clear. I wonder if I do that if I should add notes as to the location of the island or the dlc needed, but that might make it too cluttered.

2023-09-08 06:34 UTC, Greelan commented
> So for the day night setting, a minimum of one is correct, since you can't have zero time, 1 is the minimum setting and after that you it's even 10s. (not me, that's the devs, I could go on, but just look at how the console works, lol)

OK, but how about enums then? 1, 10, 20, etc

2023-09-08 06:36 UTC, JonathanArendt commented
That works, I wasn't sure which would be more clear, I'll up date that now

2023-09-08 06:37 UTC, Greelan commented
> As for the list, I used the ordering on the guide, It's listed based on the island that the player starts on (and that includes dlc bases on the dlc maps). I used the same ordering on the server setup guide, but i could change the order of it, if that makes it more clear. I wonder if I do that if I should add notes as to the location of the island or the dlc needed, but that might make it too cluttered.

Yeah, I think you need to distinguish what is DLC and what is stock. Eg for OpenRCT2 I add the prefixes `RCT1:` and `RCT2:`.

Regardless of the order that the guide lists it, it is easier for someone to find a specific island via alphabetical order, given the list is quite long - you might have it in blocks: first stock islands in alpha order, then DLC islands in alpha order

2023-09-08 06:39 UTC, JonathanArendt commented
> 

There's no way to had text delimiters in the enum list correct? like a non selected vaule to sepereate the list?

2023-09-08 06:43 UTC, Greelan commented
Afraid not

2023-09-08 07:13 UTC, Greelan commented
@IceOfWraith , over to you xD

2023-09-09 11:39 UTC, JonathanArendt commented
@IceOfWraith I will be busy this weekend, but I will probably be availible for questions, and then I'll be free on monday if needbe.

2023-09-13 02:58 UTC, IceOfWraith commented
I'm just diving into this one now. I do have a question about the note here:

`These settings can also be changed in-game if "Enable Settings Menu" under "Stormworks - World Creation" is set.`

If a user sets a setting in-game, but AMP has a setting that differs, does the setting get reverted when they restart the server since AMP isn't able to detect changes made to a settings file elsewhere?

2023-09-13 03:13 UTC, JonathanArendt commented
> 

So No Amp does not override the settings, they are only the Default setting, and only matter for world creation, the reason I have them in a seperate group is because those settings can be changed in game if the settings are enabled, however the World creation settings cannot be changed after creation.

The only settings that affect the server after creation, is the Server Settings.

2023-09-13 03:16 UTC, IceOfWraith commented
I don't own the game to see it myself, so that's why I have to rely on you to provide this info. I assume that means on first time in the game you can choose the defaults, and after that it sticks with whatever was chosen. And none of the settings under Server Settings are editable in game.

2023-09-13 03:21 UTC, JonathanArendt commented
Correct, Server/General settings (aside from Admin, Auth, and Blacklist) are not editable in game, but they do change the server when the server is started, 
World creation settings can only be set when the save is generated, you either have to specify a new save, or delete the existing save to update.
The Gameplay settings can be changed ingame if the Settings Menu is enabled for admins, otherwise they act as World Creation settings.

2023-09-13 03:23 UTC, JonathanArendt commented
If you have questions and want to discuses them, we can hop into Discord Voice Channel and I can help facilitate testing with the game, if need be.

2023-09-13 03:24 UTC, IceOfWraith commented
I don't think that's necessary so far. I see that it starts up normally in Windows and Linux. I'm going through and reviewing the settings for spelling/grammar. It looks like you did a good job at first glance. I do note some spelling mistakes, but I'll provide that all when I'm done. :)

2023-09-13 03:26 UTC, JonathanArendt commented
Sounds good, Note that the extra steps guide needs the correct url before release, I started the .md file for you, but it may need to be seriously overhauled. And it needs to be removed from the PR before pushing the changes.

2023-09-13 03:27 UTC, IceOfWraith commented
Definitely, the config file update stage will also need updated. (noting for myself) Lol

2023-09-13 03:31 UTC, JonathanArendt commented
I'm not good at technical writing, but I can help clarify the points I'm trying to get across. There are some side notes that you might want to add, The stormworks server is a defiantly a weird one. I tried to be clear on the Notes in settings menus, but idk if it could be made more clear.

2023-09-13 03:35 UTC, JonathanArendt commented
Such as this [Setting up Loopback Adapter on same network.](https://steamcommunity.com/sharedfiles/filedetails/?id=2433754130&searchtext=advanced+dedicated#:~:text=Installing%20Microsoft%20Loopback%20Adapter)

2023-09-13 03:37 UTC, IceOfWraith commented
Thanks, I hate it.

2023-09-13 03:38 UTC, JonathanArendt commented
Hate what??
The game?

2023-09-13 03:39 UTC, IceOfWraith commented
The fact you need the loopback adapter installed to see the server on the same machine. Lol

2023-09-13 03:40 UTC, JonathanArendt commented
Yeah same, It's weird, I was working on testing the RCT2 for Greelan and it was causing it to show up twice, lol.

2023-09-13 03:56 UTC, JonathanArendt commented
Hey, do you want me to go throught and add notes for review on the url's and stuff so we don't forget to change any of them.

2023-09-13 03:57 UTC, IceOfWraith commented
Way ahead of you. Give me a few more minutes and you should have your review ready. :)

2023-09-13 04:01 UTC, JonathanArendt commented
Lol sounds good, I'm used to small changes and then pushing one at a time, i thought you were just making a list, lol.

2023-09-13 04:07 UTC, JonathanArendt commented
Oh, one of the biggest things I hate about this game is the console output, not that it's neccasarily bad, cause on CMD it just clears the screan each time, it doesn't spam it, but on amp it just is spam, It would be noice if amp had IO mode that recgonises this and just updates a graft or something, but that's up to Mike to implement is that right?

2023-09-13 04:16 UTC, IceOfWraith requested changes
Let me start by saying, great job! This is a very thorough template. The main issues noted are grammar and spelling. I think I've grabbed all of them in the review. There are a few suggestions for the guide portion as well.

I'll create an article as soon as the guide portion is done so you can get a link to use for the other edits I mentioned.

Please respond with any changes or reasons why I'm wrong (which happens a lot), and we can get this merged. You can close the individual review comments as you make changes.

Again, great work on this!

2023-09-13 04:16 UTC, IceOfWraith commented on stormworksconfig.json
> +    "Description": "These settings are for world creation. They may not be able to be changed after the world is created. If needed, delete  the \"working_server\" and \"saves\" directories to genera
`They may not be changed`

2023-09-13 04:16 UTC, IceOfWraith commented on stormworksconfig.json
> +    "Description": "Sets the ammount of money the players start out with at world creation.",
`players start with`

2023-09-13 04:16 UTC, IceOfWraith commented on stormworksconfig.json
> +    "Description": "These settings are for configuring gameplay options for a world. Note that changing them may not update a save game. These settings can also be changed in-game if \"Enable Setting
`delete the` (extra space)

2023-09-13 04:16 UTC, IceOfWraith commented on stormworksguide.md
> +Simply a ban list, players can be banned in game, however, you have to remove their id from the ban list, similar to adding a player to the whitelist, however remove the `<id value="TheirID" />`.
`Simply a ban list. Players`

Can you provide details of which file has these values in it that will need removed?

2023-09-13 04:16 UTC, IceOfWraith commented on stormworksguide.md
> +The following commands can be used in game to control player permissions and to save the game. Note that the game's console does not have inputs, so commands must be ran in game. This means that ther
Does the game not have any type of autosave? That's scary if so!

2023-09-13 04:16 UTC, IceOfWraith commented on stormworksguide.md
> +There are 4 settings for player permissions. Admins, Authorized, Blacklist, and Whitelist.
Perhaps, note that you have to use the commands at the bottom to adjust these in-game? The way it reads now, I was confused what I'd do with these until I finished the whole guide.

2023-09-13 04:17 UTC, IceOfWraith commented
> Oh, one of the biggest things I hate about this game is the console output, not that it's neccasarily bad, cause on CMD it just clears the screan each time, it doesn't spam it, but on amp it just is spam, It would be noice if amp had IO mode that recgonises this and just updates a graft or something, but that's up to Mike to implement is that right?

Yupp, nothing can be done from our end on this front. He does intend to revamp the console though. So hopefully it comes out much smoother. It's been a pain point for generic forever.

2023-09-13 05:18 UTC, JonathanArendt commented
@IceOfWraith  I have resolved all of the current spelling changes, and clairied the .md file.

2023-09-13 05:20 UTC, IceOfWraith commented
Very good! I'll look again tomorrow and let you know what I see.

2023-09-13 23:30 UTC, IceOfWraith commented
It looks like there's still some items that aren't resolved. Check the conversation above and you'll see the review comments. You might need to unhide the messages since GitHub likes to shrink it.

2023-09-14 01:59 UTC, JonathanArendt commented
> It looks like there's still some items that aren't resolved. Check the conversation above and you'll see the review comments. You might need to unhide the messages since GitHub likes to shrink it.
The only conversations that i did not resolve where one's that need to be verified because I changed the text.
or the urls

2023-09-14 02:03 UTC, JonathanArendt commented
This is my first PR, so I'm not sure if there's something else that I need to do, I didn't close the URLs because they need to be changed still, and the one's where I reworded something, I didn't close it but requesed review on that item so you know where to look.

2023-09-14 02:03 UTC, IceOfWraith commented on stormworks.kvp
> +Meta.EndpointURIFormat=steam://connect/{0}
@JonathanArendt This is the first one that I don't see addressed. It either needs changed, or explanation why it wasn't changed. There are sometimes valid reasons to not do these suggestions, like if a game doesn't support a feature.

2023-09-14 02:04 UTC, IceOfWraith commented on stormworksconfig.json
> +      "0": "Auto (default)",
@JonathanArendt Here's another one.

2023-09-14 02:06 UTC, IceOfWraith commented
No need to worry. I don't mind helping you through the process. I struggled like crazy my first time. I'm pretty sure I even had to close and open a new one because I botched it so bad. Lol

I tagged you in a couple of comments, I'm not sure if that will show easily for you.

2023-09-14 02:10 UTC, JonathanArendt commented
yeah, so I did address each issue in one way or an other, And i posted comments on each one, don't know if that's how I'm supposed to, but I leaft them open because I felt like they needed discussion for resolution.\

2023-09-14 02:10 UTC, JonathanArendt commented
And i responded to you're comment's that you just posted for clearification as well.

2023-09-14 02:12 UTC, IceOfWraith commented
Hmm... I don't see your responses for some reason. Maybe I'm looking in the wrong place. x)

2023-09-14 02:12 UTC, JonathanArendt commented
Ohh

2023-09-14 02:13 UTC, JonathanArendt commented
Oh, I don't know, they all say pending?

2023-09-14 02:15 UTC, IceOfWraith commented
Ahhh okay, I think you're posting a review also. You should be able to respond directly to my comments up above here. There should be a Reply box under each one.

2023-09-14 02:15 UTC, JonathanArendt commented
![image](https://github.com/CubeCoders/AMPTemplates/assets/16638056/5e8e456b-fe81-4563-8234-04875d82726e)

2023-09-14 02:16 UTC, IceOfWraith commented
Well that's new... Let me see what's up.

2023-09-14 02:16 UTC, JonathanArendt commented on stormworks.kvp
> +Meta.EndpointURIFormat=steam://connect/{0}
That's what I was saying, Steam connect did not work, And as far as I know, the only way to connect is in game, there is no direct connect option in game.

2023-09-14 02:16 UTC, JonathanArendt commented on stormworksconfig.json
> +      "0": "Auto (default)",
I pushed changes to include the number's in parrenthese, is that acceptable?

2023-09-14 02:17 UTC, IceOfWraith commented
WOAH! There they all are. Haha

2023-09-14 02:17 UTC, JonathanArendt commented
yeah, I don't know, but now you should see everyting that I did last nigh,

2023-09-14 02:17 UTC, JonathanArendt commented
I had to post my reveiw, that's stupid, sorry, didn't know I had to do that

2023-09-14 02:20 UTC, JonathanArendt commented
![image](https://github.com/CubeCoders/AMPTemplates/assets/16638056/67213a0f-e791-4f5d-92d1-88ca90d39417)

2023-09-14 02:21 UTC, JonathanArendt commented
https://github.com/orgs/community/discussions/6893

2023-09-14 02:21 UTC, JonathanArendt commented
Apparently it's a bug/issue, idk. I've only used github for repos and personal projects with frinds, not like this.

2023-09-14 02:22 UTC, IceOfWraith commented
Oof. Well that's good to know! I haven't run into that yet on any of my reviews. (surprisingly)

Or maybe I have and Greelan just knew what I was trying to say. Haha

2023-09-14 02:22 UTC, JonathanArendt commented
Are you and greleen the only ones that make templates?

2023-09-14 02:23 UTC, IceOfWraith commented
The only regulars, yeah. We've had others submit some awesome things though. TmodLoader and mods for 7D2D were big ones others provided.

2023-09-14 02:24 UTC, JonathanArendt commented
Well, I don't mind helping, I enjoy it, It's an interesting side of coding.

2023-09-14 02:28 UTC, JonathanArendt commented
> Oof. Well that's good to know! I haven't run into that yet on any of my reviews. (surprisingly)
> 
> Or maybe I have and Greelan just knew what I was trying to say. Haha

It's almost like I have to respond and then post my response at once, so he may know that. Once I hit submit review, everything showed up at once, i don't know. I may have done it wrong thou.

2023-09-14 02:29 UTC, IceOfWraith commented
It's always appreciated! You seem to have grabbed the best parts of other templates and put them into this one which a lot of others have failed to do on their first try. So great job with it!

It's getting late here so I'll finish reviewing tomorrow, but I'm glad to see you actually had replied and it was just a glitch.

2023-09-14 02:31 UTC, JonathanArendt commented
Sounds good, The big one is the MD, it got a lot of rewrites, everything else should be resolved, the two that you pinged me on you may need to check if it's acceptable or advise on steps to be taken.

2023-09-14 02:34 UTC, JonathanArendt commented on stormworksconfig.json
> +    "Description": "Player permissions (and whitelisted players) can be set using in-game commands. See the [Stormworks Guide](https://discourse.cubecoders.com/docs?category=21) for further informati
Needs updated before merge.

2023-09-14 02:34 UTC, JonathanArendt commented on stormworksconfig.json
> +    "Description": "Sets the [Steam64 ID](https://steamidfinder.com/) of the primary (first) admin on the server. Other admins (as well as authorized users and banned users) can be added in-game. See
Needs updated before merge.

2023-09-15 01:47 UTC, JonathanArendt commented
Do you want to remove the guide from the PR as well?

2023-09-15 01:48 UTC, IceOfWraith commented
Oh yeah, go ahead and remove that also.

2023-09-15 01:59 UTC, JonathanArendt commented
All done!

2023-09-15 02:02 UTC, IceOfWraith approved these changes
Great work! Thank you for the submission!

2023-09-15 02:02 UTC, merged